do reg_one_variate.do
do lasso_and_ridge_shrinkage.do
do DID_dynamic_trend.do
do logit_and_roc.do
do nls_mpc.do
do weighted_ols.do
do qreg_outlier.do
do hcw_lasso.do
do quarterly_gdp.do
do dayly_stock_price.do
do gdp_growth.do
do stock_return.do
do stochastic_path.do
do auto_corr_gdp.do
do auto_corr_stock.do
do simulate_ma.do